### ISSUE TITLE
Message: Object of class OCA\OpenIdConnect\Application could not be converted to string

### ISSUE THREAD

**Issue by otahmasebi** [owncloud/openidconnect#112]
my owncloud status:
version | 10.5.0.10
versionstring | 10.5.0
edition | Community

i installed and configured [openidconnect 1.0.0 ](https://github.com/owncloud/openidconnect/releases/tag/v1.0.0) and i got this error after login:

Internal Server Error
The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.

Technical details
Remote Address: #########
Request ID: #########
Type: Error
Code: 0
Message: Object of class OCA\OpenIdConnect\Application could not be converted to string
File: /var/www/owncloud/lib/private/legacy/app.php
Line: 245

Trace
#0 /var/www/owncloud/lib/private/legacy/app.php(190): OC_App::requireAppFile()
#1 /var/www/owncloud/lib/private/legacy/app.php(124): OC_App::loadApp()
#2 /var/www/owncloud/lib/base.php(886): OC_App::loadApps()
#3 /var/www/owncloud/index.php(54): OC::handleRequest()
#4 {main}

**Comment by otahmasebi** [comment]
thanks, problem solved.
