### ISSUE TITLE
Failing to login with corporate proxy between Owncloud and the IdP

### ISSUE THREAD

**Issue by jdcano-bpe** [owncloud/openidconnect#146]
Hello,

Thanks a lot for all the efforts you are doing with this app for Owncloud, is really useful.

I am having a problem to login using the OpenID app with Azure OpenID cloud. So far, the problem I have is with the proxy configuration. In my case the access to the IDP is outside our network and behind a firewall, therefore, in order to access to the IDP (login.microsoftonline.com) I have to pass through our corporate proxy, this is my configuration file:

``` 
<?php
$CONFIG = array (
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'owncloud-owncloud-dev.example.com',
    2 => 'login.microsoftonline.com',
    3 => 'graph.microsoft.com',
  ),
  'datadirectory' => '/var/lib/owncloud/files',
  'dbtype' => 'mysql',
  'dbhost' => 'mariadb:3306',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => '***********',
  'dbtableprefix' => 'oc_',
  'log_type' => 'owncloud',
  'supportedDatabases' =>
  array (
    0 => 'sqlite',
    1 => 'mysql',
    2 => 'pgsql',
  ),
  'upgrade.disable-web' => true,
  'default_language' => 'en',
  'overwrite.cli.url' => 'https://owncloud-owncloud-dev.example.com',
  'htaccess.RewriteBase' => '/',
  'logfile' => '/dev/stdout',
  'loglevel' => 2,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'redis',
    'port' => '6379',
  ),
  'passwordsalt' => '*********************',
  'secret' => 'a***************************',
  'version' => '10.6.0.5',
  'mysql.utf8mb4' => true,
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'xxxxxxxx',
  'mail_domain' => 'example.com',
  'mail_from_address' => 'owncloud-dev',
  'mail_smtpmode' => 'smtp',
  'proxy' => 'http://proxy.example.com:8080/',
  'mail_smtphost' => 'gvamail.example.com',
  'mail_smtpport' => '25',
  'maintenance' => false,
  'openid-connect' =>
  array (
    'provider-url' => 'https://login.microsoftonline.com//',
    'client-id' => '***************************',
    'client-secret' => '**************************',
    'redirect-url' => 'https://owncloud-owncloud-dev.example.com/index.php/apps/openidconnect/redirect',
    'loginButtonName' => 'Santander Private Bankin SSO Login',
    'autoRedirectOnLoginPage' => false,
    'mode' => 'userid', // change this to 'email' if necessary (see Identity Provider configuration)
    'search-attribute' => 'preferred_username', // change this to suit your environment (see Identity Provider configuration)
    'post_logout_redirect_uri' => 'https://owncloud-owncloud-dev.example.com/',
    'provider-params' =>
    array (
      'authorization_endpoint' => 'https://login.microsoftonline.com/a******/oauth2/v2.0/authorize',
      'token_endpoint' => 'https://login.microsoftonline.com/******/oauth2/v2.0/token',
      //'token_endpoint_auth_methods_supported' => ['client_secret_post','private_key_jwt','client_secret_basic'],
      'userinfo_endpoint' => 'https://graph.microsoft.com/oidc/userinfo',
      'end_session_endpoint' => 'https://login.microsoftonline.com/************/oauth2/v2.0/logout',
      'jwks_uri' => 'https://login.microsoftonline.com/********/discovery/v2.0/keys',
    ),
  ),
); 
```
When I click on the OpenID button to login, all goes well, and I am able to login but when it tries to redirect to Owncloud again, it does not works, I have the following error in the logs:

```
[Mon Mar 08 18:35:42.071322 2021] [php7:notice] [pid 67627] [client XXX.XXX.XXX.XXX:0] {"reqId":"8IKwkagBWkiFobgfwWw4","level":3,"time":"2021-03-08T18:35:42+00:00","remoteAddr":"XX.XX.XX.XX","user":"--","app":"index","method":"GET","url":"\\/index.php\\/apps\\/openidconnect\\/config","message":"Exception: {\\"Exception\\":\\"Jumbojett\\\\\\\\OpenIDConnectClientException\\",\\"Message\\":\\"Curl error: (28) Failed to connect to login.microsoftonline.com port 443: Connection timed out\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/var\\\\\\/lib\\\\\\/owncloud\\\\\\/apps\\\\\\/openidconnect\\\\\\/lib\\\\\\/Client.php(149): Jumbojett\\\\\\\\OpenIDConnectClient->fetchURL()\\\\n#1 \\\\\\/var\\\\\\/lib\\\\\\/owncloud\\\\\\/apps\\\\\\/openidconnect\\\\\\/lib\\\\\\/Client.php(97): OCA\\\\\\\\OpenIdConnect\\\\\\\\Client->fetchURL()\\\\n#2 \\\\\\/var\\\\\\/lib\\\\\\/owncloud\\\\\\/apps\\\\\\/openidconnect\\\\\\/lib\\\\\\/Controller\\\\\\/LoginFlowController.php(102): OCA\\\\\\\\OpenIdConnect\\\\\\\\Client->getWellKnownConfig()\\\\n#3 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/Http\\\\\\/Dispatcher.php(153): OCA\\\\\\\\OpenIdConnect\\\\\\\\Controller\\\\\\\\LoginFlowController->config()\\\\n#4 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/Http\\\\\\/Dispatcher.php(85): OC\\\\\\\\AppFramework\\\\\\\\Http\\\\\\\\Dispatcher->executeController()\\\\n#5 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/App.php(100): OC\\\\\\\\AppFramework\\\\\\\\Http\\\\\\\\Dispatcher->dispatch()\\\\n#6 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/AppFramework\\\\\\/Routing\\\\\\/RouteActionHandler.php(47): OC\\\\\\\\AppFramework\\\\\\\\App::main()\\\\n#7 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Route\\\\\\/Router.php(342): OC\\\\\\\\AppFramework\\\\\\\\Routing\\\\\\\\RouteActionHandler->__invoke()\\\\n#8 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/lib\\\\\\/base.php(917): OC\\\\\\\\Route\\\\\
--
  | \\\Router->match()\\\\n#9 \\\\\\/var\\\\\\/www\\\\\\/owncloud\\\\\\/index.php(54): OC::handleRequest()\\\\n#10 {main}\\",\\"File\\":\\"\\\\\\/var\\\\\\/lib\\\\\\/owncloud\\\\\\/apps\\\\\\/openidconnect\\\\\\/vendor\\\\\\/jumbojett\\\\\\/openid-connect-php\\\\\\/src\\\\\\/OpenIDConnectClient.php\\",\\"Line\\":1207}"}
```

From my firewall logs, I can see that the traffic between the Owncloud and the IDP (login.microsoftonline.com) is blocked, but the proxy in Owncloud is configured and I can access to the update services and market place as well. If I try to access the IDP using the proxy with curl I can do it without problems. 

```
/var/www/owncloud # curl -kv https://login.microsoftonline.com
*   Trying 20.190.160.5:443...
* TCP_NODELAY set
```
```
/var/www/owncloud # curl -kv --proxy http://proxy.example.com:8080  https://login.microsoftonline.com
*   Trying proxy.example.com:8080...
* TCP_NODELAY set
* Connected to proxy.example.com port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to login.microsoftonline.com:443
* Proxy auth using Basic with user 'proxy'
> CONNECT login.microsoftonline.com:443 HTTP/1.1
> Host: login.microsoftonline.com:443
> Proxy-Authorization: Basic *********
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Date: Mon, 08 Mar 2021 18:52:17 GMT
< Proxy-Connection: Keep-Alive
< Via: 1.1 proxy.example.com
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; CN=stamp2.login.microsoftonline.com
*  start date: Mar  5 00:00:00 2021 GMT
*  expire date: Mar  5 23:59:59 2022 GMT
*  issuer: C=CH; ST=GE; L=Geneva; 
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> GET / HTTP/1.1
> Host: login.microsoftonline.com
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Cache-Control: no-store, no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Expires: -1
< Location: https://www.office.com/login#
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
< x-ms-request-id: 5543ab87-f9af-4fef-b07b-7a814bd3ac00
< x-ms-ests-server: 2.1.11530.15 - NEULR2 ProdSlices
< Set-Cookie: fpc=ApN_sfEUbm5Pqb73571r-tk; expires=Wed, 07-Apr-2021 18:52:18 GMT; path=/; secure; HttpOnly; SameSite=None
< Set-Cookie: esctx=AQABAAAAAAD--DLA3VO7QrddgJg7Wevriq2Y4st546ZdgizifuRv5Hi_tjP5wJhE6npoNHjWeUK9E8eeBBq0XBVBxi3fLigt-iE9iS-5BfThl_wcgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
< Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
< Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
< Date: Mon, 08 Mar 2021 18:52:17 GMT
< Content-Length: 146
< Age: 2
< Via: HTTPS/1.1 proxy.example.com
<
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://www.office.com/login#">here</a>.</h2>
</body></html>
* Connection #0 to host proxy.example.com left intact
```
I tried adding the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY without success. 

So my question is:

**Is there a way to configure the Owncloud OpenID app to use the global proxy configuration?** **Or there is something else I am missing?**

Thanks a lot in advance,
Best regards,
Daniel

**Comment by DeepDiver1975** [comment]
proxy support has not been implemented ...
this is the code block where proxy support can be added by using owncloud's http client which uses the configured proxy
https://github.com/owncloud/openidconnect/blob/e6cb00e6405046e282155b7b3abd7b12f224d2f5/lib/Client.php#L148
