### ISSUE TITLE
PKCE code error

### ISSUE THREAD

**Issue by tbs575** [owncloud/openidconnect#218]
I am not sure what's wrong. please help , thanks
* using keycloak with ssl provide openid service, I login owncloud for the first time and meet error 'Error in OpenIdConnect:PKCE code verifier not specified' and check owncloud log (please see follow information).

```
{"reqId":"nz2q5F1B0D8xbgL0MxeJ","level":3,"time":"2022-03-11T05:46:22+00:00","remoteAddr":"192.168.160.2","user":"--","app":"OpenID","method":"GET","url":"\/apps\/openidconnect\/redirect?state=b96ed9bcc1ac23a8f556ec98d3138c07&session_state=c8cbc2d3-97c3-4b00-9e51-eebe243c55af&code=e54c3d1b-6a87-47a3-9fb5-8bafc15b00ff.c8cbc2d3-97c3-4b00-9e51-eebe243c55af.2acc1fd5-cd2d-4f4e-b132-f056e953e971","message":"Exception: {\"Exception\":\"JuliusPC\\\\OpenIDConnectClientException\",\"Message\":\"PKCE code verifier not specified\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/lib\\\/Client.php(206): JuliusPC\\\\OpenIDConnectClient->authenticate()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/lib\\\/Controller\\\/LoginFlowController.php(125): OCA\\\\OpenIdConnect\\\\Client->authenticate()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(170): OCA\\\\OpenIdConnect\\\\Controller\\\\LoginFlowController->login(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(927): OC\\\\Route\\\\Router->match()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/vendor\\\/juliuspc\\\/openid-connect-php\\\/src\\\/OpenIDConnectClient.php\",\"Line\":339}"}
```
* and I login for the second time, that's OK, I can saw file in owncloud server.  but when I logout from owncloud, try login again, still meet error 'Error in OpenIdConnect:PKCE code verifier not specified'

**Comment by DeepDiver1975** [comment]
You need to change the same site cookie setting im config.php. please check readme

**Comment by tbs575** [comment]
@DeepDiver1975 thanks, as I use docker's owncloud, so I set enviroment `OWNCLOUD_HTTP_COOKIE_SAMESITE: 'None' `, but still met issue

**Comment by tbs575** [comment]
> You need to change the same site cookie setting im config.php. please check readme

thanks, as I use docker's owncloud, so I set enviroment OWNCLOUD_HTTP_COOKIE_SAMESITE: 'None' , but still met issue
