### ISSUE TITLE
openid signsout after signing in

### ISSUE THREAD

**Issue by suhaylhallim** [owncloud/openidconnect#76]
I suppose this might be caused by the design of the idP Server I'm using.

### **Issues**
According to the owncloud.log file, 
1 - The array of data provided to this app is incorrectly structured.
2 - Undefined Index of "use-token-introspection-endpoint". (probably because the data array is incorrect)
3 - The token cannot be verified.
4 - The provider revocation_endpoint could not be fetched. (I'm sure my well known uri is correct)

### **My Experience**
When I click the Open ID Connect button, I am taken to my idP login page to login. After signing in, I am redirected to the global logout uri that is set in the idP. It doesn't redirect to the owncloud domain/sub-domain at all. This in turn signs me out of the idP without me every triggering the logout at all. Please find more information below. 

### **owncloud.log output**
```
{"reqId":"4hqes3jbriI4qIRg7eV7","level":3,"time":"2020-04-26T04:59:36+00:00","remoteAddr":"192.168.1.40","user":"--","app":"PHP","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?code=_777DybYgKGNbMNQLlMAYqp5-FsdTi-AGFMFoA30KT8&state=25fa60802810a61494f6b40c697779d1&userState=Authenticated","message":"in_array() expects parameter 2 to be array, string given at \/var\/www\/owncloud\/apps-external\/openidconnect\/vendor\/jumbojett\/openid-connect-php\/src\/OpenIDConnectClient.php#715"}
{"reqId":"dzJsx28996sQ2JhePrRq","level":3,"time":"2020-04-26T04:59:36+00:00","remoteAddr":"192.168.1.40","user":"johndoe","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Undefined index: use-token-introspection-endpoint at \/var\/www\/owncloud\/apps-external\/openidconnect\/lib\/SessionVerifier.php#99"}
{"reqId":"dzJsx28996sQ2JhePrRq","level":3,"time":"2020-04-26T04:59:36+00:00","remoteAddr":"192.168.1.40","user":"johndoe","app":"OpenID","method":"GET","url":"\/index.php\/apps\/files\/","message":"Token cannot be verified: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFjY2IwZWI0NDkifQ.eyJhdWQiOiJmNGI2ZTZlZi1mYzg5LTQxZTItODQzOC01MTVhOGUxYjBmYzgiLCJleHAiOjE1ODc4ODA3NzYsImlhdCI6MTU4Nzg3NzE3NiwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiI5NTM1ZDI3Mi0wNmE4LTQzNjQtYTQ1Zi1jOGYzN2JiZTMxYzAiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoic3VoYXlsaGFsbGltQGhhbGxpbXNvZnQuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6InN1aGF5bGhhbGxpbSIsImFwcGxpY2F0aW9uSWQiOiJmNGI2ZTZlZi1mYzg5LTQxZTItODQzOC01MTVhOGUxYjBmYzgiLCJyb2xlcyI6WyJhZG1pbiJdfQ.7iJ6vUUEmvadBPAi4byy6l3o1Zl8_9QLt5KFW_ZYqeM"}
{"reqId":"dzJsx28996sQ2JhePrRq","level":3,"time":"2020-04-26T04:59:36+00:00","remoteAddr":"192.168.1.40","user":"johndoe","app":"OpenID","method":"GET","url":"\/index.php\/apps\/files\/","message":"Calling Application:logout"}
{"reqId":"dzJsx28996sQ2JhePrRq","level":3,"time":"2020-04-26T04:59:36+00:00","remoteAddr":"192.168.1.40","user":"--","app":"OpenID","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"Jumbojett\\\\OpenIDConnectClientException\",\"Message\":\"The provider revocation_endpoint could not be fetched. Make sure your provider has a well known configuration available.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/vendor\\\/jumbojett\\\/openid-connect-php\\\/src\\\/OpenIDConnectClient.php(482): Jumbojett\\\\OpenIDConnectClient->getWellKnownConfigValue('revocation_endp...', NULL)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/vendor\\\/jumbojett\\\/openid-connect-php\\\/src\\\/OpenIDConnectClient.php(1383): Jumbojett\\\\OpenIDConnectClient->getProviderConfigValue('revocation_endp...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/lib\\\/SessionVerifier.php(137): Jumbojett\\\\OpenIDConnectClient->revokeToken('eyJhbGciOiJIUzI...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/lib\\\/SessionVerifier.php(88): OCA\\\\OpenIdConnect\\\\SessionVerifier->afterLogout('eyJhbGciOiJIUzI...', 'eyJhbGciOiJIUzI...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(212): OCA\\\\OpenIdConnect\\\\SessionVerifier->OCA\\\\OpenIdConnect\\\\{closure}(Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent), 'user.afterlogou...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(44): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'user.afterlogou...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(53): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('user.afterlogou...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(1088): OC\\\\User\\\\Session->emittingCall(Object(Closure), Array, 'user', 'logout')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/lib\\\/SessionVerifier.php(190): OC\\\\User\\\\Session->logout()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/lib\\\/SessionVerifier.php(121): OCA\\\\OpenIdConnect\\\\SessionVerifier->logout()\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/lib\\\/Application.php(79): OCA\\\\OpenIdConnect\\\\SessionVerifier->verifySession()\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/appinfo\\\/app.php(25): OCA\\\\OpenIdConnect\\\\Application->boot()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(239): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(190): OC_App::requireAppFile(Object(OCA\\\\OpenIdConnect\\\\Application))\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): OC_App::loadApp('openidconnect')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(881): OC_App::loadApps(Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps-external\\\/openidconnect\\\/vendor\\\/jumbojett\\\/openid-connect-php\\\/src\\\/OpenIDConnectClient.php\",\"Line\":520}"}
```

### **idP Config** (FusionAuth -> [LINK](https://fusionauth.io/))
![Capture](https://user-images.githubusercontent.com/25756641/80299070-8a4a7600-875f-11ea-88f1-f3f3d77daba0.PNG)

### **Owncloud Config**
```
'openid-connect' => [
        'provider-url' => 'https://domain-masked.com',
        'client-id' => 'VALUE MASKED',
        'client-secret' => 'VALUE MASKED',
        'loginButtonName' => Open ID Connect',
        'provider-params' => [
                'authorization_endpoint' => 'https://domain-masked.com/oauth2/authorize',
                'token_endpoint' => 'https://domain-masked.com/oauth2/token',
                'token_endpoint_auth_methods_supported' => 'client_secret_post',
                'userinfo_endpoint' => 'https://domain-masked.com/oauth2/userinfo',
//                      'registration_endpoint' => '...',
                'end_session_endpoint' => 'https://domain-masked.com/oauth2/logout',
                'jwks_uri' => 'https://domain-masked.com/.well-known/openid-configuration'
        ],
  ],
```

NOTE: I comment out the registration_endpoint because my idP doesn't seem to have one.

### **My Question**
Is there anything I can do to solve this issue or is that a compatibility issue between the app and my idP of choice?

**Comment by DeepDiver1975** [comment]
>         'provider-params' => [
>                 'authorization_endpoint' => 'https://domain-masked.com/oauth2/authorize',
>                 'token_endpoint' => 'https://domain-masked.com/oauth2/token',
>                 'token_endpoint_auth_methods_supported' => 'client_secret_post',
>                 'userinfo_endpoint' => 'https://domain-masked.com/oauth2/userinfo',
> //                      'registration_endpoint' => '...',
>                 'end_session_endpoint' => 'https://domain-masked.com/oauth2/logout',
>                 'jwks_uri' => 'https://domain-masked.com/.well-known/openid-configuration'
>         ],

You only need to set these up if the idp is no supporting well-known url - check if this exists: https://domain-masked.com/.well-known/openid-configuration

**Comment by suhaylhallim** [comment]
I solved this issue.

I removed the "provider-params" from my config file and i was presented with another error.

**Error after removing "provider-params"**
![01](https://user-images.githubusercontent.com/25756641/80413168-05fe0d00-889d-11ea-8209-1e9bbacd356c.png)

### **Solution to this problem**
Once again, this problem might be specific to the idP I am using/ any idP that requires lots of manual config.

I had to enable the JWT option under the client config of the idP. I also had to assign an "Access token signing key" & "Id token signing key". I just selected the "Auto generate a new key on save…" option for both of options. This will auto generate a new key and assign it to the respected option on save, for both options. (See `# 1` & `# 2` in the image below for reference)
![02](https://user-images.githubusercontent.com/25756641/80414325-de0fa900-889e-11ea-8cb9-8afecb1af27d.png)

### **After signing out of OwnCloud, idP is not sign out automatically**
I had to include the "end_session_endpoint" in the OwnCloud config.
```
'provider-params' => [
            'end_session_endpoint' => 'https://domain-masked.com/oauth2/logout',
],
```

### **Other Errors**
I encountered other errors and decided to include them and the solution below

**"Error in OpenIdConnect:Unable to verify signature" on the Owncloud login page after authenticating.**
This happens when JWT is enabled on the idP but default signing keys are used. The solution is to generate specific signing keys for OwnCloud as specified above.

**"Error in OpenIdConnect:Unable to find a key for (algorithm, kid):RS256, FuAF4kddEikhTvrlf1KIdhW2jow)" on the Owncloud login page after authenticating.**
This happens when the jwks_uri is defined in the OwnCloud config file. Just remove it.
